"""Docker build / push / deploy profile."""

from __future__ import annotations

from pathlib import Path


def render_ci(_project_dir: Path) -> str:
    return """# Generated by Fast-Git (profile: docker)
stages:
  - build
  - push
  - deploy

build:
  stage: build
  tags:
    - docker
  script:
    - |
      if [ -f compose.yml ]; then
        docker compose -f compose.yml build
      elif [ -f Dockerfile ]; then
        docker build -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA" .
      else
        echo "No compose.yml or Dockerfile found" && exit 1
      fi

push:
  stage: push
  tags:
    - docker
  script:
    - |
      if [ -n "${CI_REGISTRY_IMAGE:-}" ] && [ -f Dockerfile ]; then
        docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"
      else
        echo "Skipping registry push (no CI_REGISTRY_IMAGE / Dockerfile)"
      fi
  only:
    - main
    - master

deploy:
  stage: deploy
  tags:
    - deploy
  script:
    - echo "Wire deploy to your target (e.g. docker compose up -d)"
  only:
    - main
    - master
"""
