"""Fast-* family profile: CI stages call the project's own __ctrl__ scripts."""

from __future__ import annotations

from pathlib import Path

from lib.seed import detect_ctrl_script


def render_ci(project_dir: Path) -> str:
    ctrl = detect_ctrl_script(project_dir)
    if not ctrl:
        raise SystemExit(
            f"fast-family profile requires __ctrl__/*-ctrl.sh in {project_dir}"
        )
    ctrl_path = f"__ctrl__/{ctrl}"
    return f"""# Generated by Fast-Git (profile: fast-family)
stages:
  - test
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2

test:
  stage: test
  tags:
    - docker
  script:
    - bash {ctrl_path} test all

build:
  stage: build
  tags:
    - docker
  script:
    - docker compose -f compose.yml build

deploy:
  stage: deploy
  tags:
    - deploy
  script:
    - bash __ctrl__/remote/start-prod.sh
  only:
    - main
    - master
"""
