"""Generic Python project CI profile."""

from __future__ import annotations

from pathlib import Path


def render_ci(_project_dir: Path) -> str:
    return """# Generated by Fast-Git (profile: python)
stages:
  - install
  - test
  - deploy

install:
  stage: install
  script:
    - python -m pip install --upgrade pip
    - |
      if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      if [ -f pyproject.toml ]; then pip install -e ".[dev]" || pip install -e .; fi

test:
  stage: test
  script:
    - |
      if [ -d tests ] || [ -d test ]; then
        python -m pytest -q || python -m unittest discover -q
      else
        echo "No tests/ directory — skipping"
      fi

deploy:
  stage: deploy
  script:
    - echo "Add deploy steps for this project"
  only:
    - main
    - master
"""
